insert into authors (name, link) values ('Rafael', 'https://es.wikipedia.org/wiki/Rafael_Sanzio');
insert into authors (name, link) values ('Leonardo Da Vinci', 'https://es.wikipedia.org/wiki/Leonardo_da_Vinci');
insert into authors (name, link) values ('Diego Velázquez', 'https://es.wikipedia.org/wiki/Diego_Vel%C3%A1zquez');
insert into authors (name, link) values ('Rembrandt', 'https://es.wikipedia.org/wiki/Rembrandt');
insert into authors (name, link) values ('Francisco de Goya', 'https://es.wikipedia.org/wiki/Francisco_de_Goya');
insert into authors (name, link) values ('J. M. W. Turner', 'https://es.wikipedia.org/wiki/J._M._W._Turner');
insert into authors (name, link) values ('Edouard Manet', 'https://es.wikipedia.org/wiki/%C3%89douard_Manet');
insert into authors (name, link) values ('Claude Monet', 'https://es.wikipedia.org/wiki/Claude_Monet');
insert into authors (name, link) values ('Pierre-Auguste Renoir', 'https://es.wikipedia.org/wiki/Pierre-Auguste_Renoir');
insert into authors (name, link) values ('Vincent Van Gogh', 'https://es.wikipedia.org/wiki/Vincent_van_Gogh');
insert into authors (name, link) values ('Paul Cézanne', 'https://es.wikipedia.org/wiki/Paul_C%C3%A9zanne');
insert into authors (name, link) values ('Picasso', 'https://es.wikipedia.org/wiki/Pablo_Picasso');
insert into authors (name, link) values ('Vasili Kandinsky', 'https://es.wikipedia.org/wiki/Vasili_Kandinski');
insert into authors (name, link) values ('Piet Mondrian', 'https://es.wikipedia.org/wiki/Piet_Mondrian');
insert into authors (name, link) values ('Morris Louis', 'https://es.wikipedia.org/wiki/Morris_Louis');
insert into authors (name, link) values ('Salvador Dalí', 'https://es.wikipedia.org/wiki/Salvador_Dal%C3%AD');
insert into authors (name, link) values ('René Magritte', 'https://es.wikipedia.org/wiki/Ren%C3%A9_Magritte');
insert into authors (name, link) values ('Edvard Munch', 'https://es.wikipedia.org/wiki/Edvard_Munch');
insert into authors (name, link) values ('Edward Hopper', 'https://es.wikipedia.org/wiki/Edward_Hopper');
insert into authors (name, link) values ('William Holbrook Beard', 'https://en.wikipedia.org/wiki/William_Holbrook_Beard');
insert into authors (name, link) values ('Mark Ryden', 'https://es.wikipedia.org/wiki/Mark_Ryden');
