insert into styles (name) values ('Proto-Renacimiento');
insert into styles (name) values ('Quattrocento');
insert into styles (name) values ('Cinquecento');
insert into styles (name) values ('Manierismo');
insert into styles (name) values ('Renacimiento del norte de Europa');
insert into styles (name) values ('Barroco');
insert into styles (name) values ('Rococó');
insert into styles (name) values ('Neoclasicismo');
insert into styles (name) values ('Romanticismo');
insert into styles (name) values ('Realismo');
insert into styles (name) values ('Impresionismo');
insert into styles (name) values ('Postimpresionismo');
insert into styles (name) values ('Simbolismo');
insert into styles (name) values ('Primitivismo');
insert into styles (name) values ('Art Nouveau');
insert into styles (name) values ('Art Decó');
insert into styles (name) values ('Orientalismo');
insert into styles (name) values ('Fauvismo');
insert into styles (name) values ('Futurismo');
insert into styles (name) values ('Expresionismo');
insert into styles (name) values ('Cubismo');
insert into styles (name) values ('Dadaísmo');
insert into styles (name) values ('Nueva objetividad');
insert into styles (name) values ('Suprematismo');
insert into styles (name) values ('Constructivismo');
insert into styles (name) values ('Arte abstracto');
insert into styles (name) values ('Pintura metafísica');
insert into styles (name) values ('Surrealismo');
insert into styles (name) values ('Orfismo');
insert into styles (name) values ('Neoplasticismo');
insert into styles (name) values ('Precisionismo');
insert into styles (name) values ('Expresionismo abstracto');
insert into styles (name) values ('Art brut');
insert into styles (name) values ('Informalismo');
insert into styles (name) values ('Nueva figuración');
insert into styles (name) values ('Arte cinético');
insert into styles (name) values ('Op-Art');
insert into styles (name) values ('Pop-Art');
insert into styles (name) values ('Nouveau Réalisme');
insert into styles (name) values ('Nuevo Realismo');
insert into styles (name) values ('Realismo social');
insert into styles (name) values ('Arte conceptual');
insert into styles (name) values ('Minimalismo');
insert into styles (name) values ('Acción');
insert into styles (name) values ('Hiperrealismo');
insert into styles (name) values ('Postmodernidad');
insert into styles (name) values ('Street Art');
insert into styles (name) values ('Land Art');
insert into styles (name) values ('Arte Povera');
